# This is quick action to build exe and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build nightly

on:
  workflow_dispatch:
  push:
    branches:
      - prerelease

jobs:
  build:
    strategy:
      matrix:
        include:
          # macOS
          - os: macos-13
            arch: x86_64
            runs-on: macos-13
          - os: macos-latest
            arch: arm64
            runs-on: macos-latest
          # Linux
          - os: ubuntu-22.04
            arch: x86_64
            runs-on: ubuntu-22.04
          - os: ubuntu-24.04-arm
            arch: arm64
            runs-on: ubuntu-24.04-arm
          # Windows
          - os: windows-latest
            arch: x86_64
            runs-on: windows-latest
          - os: windows-11-arm
            arch: arm64
            runs-on: windows-11-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dart-lang/setup-dart@v1.7.1
      - run: dart pub get
      - name: Get version
        id: version
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
          VERSION=$(powershell -Command "(Get-Content pubspec.yaml | Select-String '^version:').ToString().Split(':')[1].Trim()")
          else
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | cut -d' ' -f2)
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build exe
        id: build_exe
        shell: bash
        run: |
          version=${{ steps.version.outputs.version }}
          osname=${{ matrix.os }}
          # Normalize osname and append arch for output file
          if [[ "$osname" == "ubuntu-22.04" ]]; then
            osname=linux-x86_64
          elif [[ "$osname" == "ubuntu-24.04-arm" ]]; then
            osname=linux-arm64
          elif [[ "$osname" == "macos-latest" ]]; then
            osname=macos-arm64
          elif [[ "$osname" == "macos-13" ]]; then
            osname=macos-x86_64
          elif [[ "$osname" == "windows-latest" ]]; then
            osname=windows-x86_64
          elif [[ "$osname" == "windows-11-arm" ]]; then
            osname=windows-arm64
          fi
          outname=gpth-v$version-nightly-$osname
          if [[ "$osname" == windows-* ]]; then
            outname="$outname.exe"
          fi
          echo "outname=$outname" >> $GITHUB_OUTPUT
          dart compile exe bin/gpth.dart -o ./$outname
      - name: Upload exe as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ steps.version.outputs.version }}-${{ steps.build_exe.outputs.outname }}
          path: ./${{ steps.build_exe.outputs.outname }}
          if-no-files-found: error
