name: gpth
description: 'Tool to help you with exporting stuff from Google Photos'
version: 4.1.0
homepage: 'https://github.com/Xentraxx/GooglePhotosTakeoutHelper'
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  # CLI and Core dependencies - Dart 3.5.4 compatible versions
  args: ^2.3.0
  path: 1.9.0
  mime: ^1.0.0
  collection: ^1.16.0
  convert: ^3.0.0
  crypto: ^3.0.0
  console_bars: ^1.0.0
  intl: ^0.17.0
  exif_reader: ^2.0.0
  image: ^3.0.0
  emoji_regex: ^0.0.3
  archive: ^3.0.0
  proper_filesize: ^1.0.0
  unorm_dart: ^0.2.0
  win32: 4.1.4
  ffi: ^1.2.0
  coordinate_converter: ^1.0.0
  
  # Flutter GUI dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  material_color_utilities: ^0.5.0
  file_picker: ^5.0.0
  flutter_riverpod: ^2.0.0
  go_router: ^10.0.0
  percent_indicator: ^4.0.0
  animations: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.20.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
